// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stardust.Flux.CoreApi.Models;

namespace Stardust.Flux.CoreApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Stardust.Flux.CoreApi.Models.Entity.AdditionalSlotData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<int>("SlotId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SlotId");

                    b.ToTable("AdditionalSlotData");
                });

            modelBuilder.Entity("Stardust.Flux.CoreApi.Models.Entity.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Hostname")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.HasKey("ServerId");

                    b.ToTable("Server");
                });

            modelBuilder.Entity("Stardust.Flux.CoreApi.Models.Entity.Slot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("SlotId");

                    b.HasIndex("ServerId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("Stardust.Flux.CoreApi.Models.Entity.AdditionalSlotData", b =>
                {
                    b.HasOne("Stardust.Flux.CoreApi.Models.Entity.Slot", "Slot")
                        .WithMany("AdditionalsData")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Stardust.Flux.CoreApi.Models.Entity.Slot", b =>
                {
                    b.HasOne("Stardust.Flux.CoreApi.Models.Entity.Server", "Server")
                        .WithMany("Slots")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Stardust.Flux.CoreApi.Models.Entity.Server", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Stardust.Flux.CoreApi.Models.Entity.Slot", b =>
                {
                    b.Navigation("AdditionalsData");
                });
#pragma warning restore 612, 618
        }
    }
}
