version: "3.4"

networks:
  dockerapi-dev:
    driver: bridge

services:
  postgres_image:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "stardust_user"
      POSTGRES_PASSWORD: "stardust_user"
      POSTGRES_DB: "stardDustdb"
      PGDATA: /tmp
    networks:
      - dockerapi-dev
  rabbitmq:
    container_name: stardust-rabbit
    image: rabbitmq:3-management
    hostname: stardust-rabbit
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  pgdata:
    external: true
